export const columnDefs = [
  { headerName: "ID", field: "id", width: 70, sortable: true },
  {
    headerName: "First Name",
    field: "firstName",
    editable: true,
    flex: 1,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Last Name",
    field: "lastName",
    editable: true,
    flex: 1,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Email",
    field: "email",
    editable: true,
    flex: 1.5,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Department",
    field: "department",
    editable: true,
    width: 150,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Position",
    field: "position",
    editable: true,
    width: 150,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Salary",
    field: "salary",
    editable: true,
    width: 120,
    sortable: true,
    filter: "agNumberColumnFilter",
    valueFormatter: (params) => `$${params.value}`,
  },
  {
    headerName: "Location",
    field: "location",
    editable: true,
    width: 120,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Status",
    field: "isActive",
    editable: true,
    width: 100,
    sortable: true,
    filter: true,
  },
];
