export const columnDefs = [
  {
    headerName: "ID",
    field: "id",
    width: 90,
    sortable: true,
    filter: true,
    pinned: "left",
  },
  {
    headerName: "Name",
    field: "name",
    flex: 1,
    editable: true,
    sortable: true,
    filter: true,
    minWidth: 150,
  },
  {
    headerName: "Email",
    field: "email",
    flex: 1.5,
    editable: true,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Role",
    field: "role",
    width: 140,
    editable: true,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Status",
    field: "status",
    width: 120,
    sortable: true,
    filter: true,
  },
  {
    headerName: "Last Login",
    field: "lastLogin",
    width: 140,
    sortable: true,
    filter: "agDateColumnFilter",
  },
  {
    headerName: "Revenue",
    field: "revenue",
    width: 120,
    sortable: true,
    filter: "agNumberColumnFilter",
    valueFormatter: (params) => `$${params.value}`,
  },
];
