export const initialData = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    role: "Product Manager",
    status: "active",
    lastLogin: "2025-09-28",
    revenue: 12000,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    role: "Engineer",
    status: "active",
    lastLogin: "2025-10-01",
    revenue: 8500,
  },
  {
    id: 3,
    name: "Carla Gomez",
    email: "carla.gomez@example.com",
    role: "Designer",
    status: "paused",
    lastLogin: "2025-09-15",
    revenue: 4200,
  },
  {
    id: 4,
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    role: "QA",
    status: "active",
    lastLogin: "2025-10-03",
    revenue: 3000,
  },
  {
    id: 5,
    name: "Esha Patel",
    email: "esha.patel@example.com",
    role: "Engineer",
    status: "active",
    lastLogin: "2025-09-29",
    revenue: 9100,
  },
  {
    id: 6,
    name: "Farah Khan",
    email: "farah.khan@example.com",
    role: "Support",
    status: "inactive",
    lastLogin: "2025-08-02",
    revenue: 1200,
  },
  {
    id: 7,
    name: "George Brown",
    email: "george.brown@example.com",
    role: "DevOps",
    status: "active",
    lastLogin: "2025-10-02",
    revenue: 7400,
  },
  {
    id: 8,
    name: "Hiro Tanaka",
    email: "hiro.tanaka@example.com",
    role: "Engineer",
    status: "paused",
    lastLogin: "2025-09-11",
    revenue: 5300,
  },
  {
    id: 9,
    name: "Isla Moore",
    email: "isla.moore@example.com",
    role: "Analyst",
    status: "active",
    lastLogin: "2025-10-04",
    revenue: 6600,
  },
  {
    id: 10,
    name: "Jack Wilson",
    email: "jack.wilson@example.com",
    role: "Sales",
    status: "active",
    lastLogin: "2025-09-30",
    revenue: 15000,
  },
  {
    id: 11,
    name: "Kiran Rao",
    email: "kiran.rao@example.com",
    role: "Engineer",
    status: "active",
    lastLogin: "2025-10-05",
    revenue: 9800,
  },
  {
    id: 12,
    name: "Lina Nguyen",
    email: "lina.nguyen@example.com",
    role: "Designer",
    status: "inactive",
    lastLogin: "2025-07-22",
    revenue: 2200,
  },
  {
    id: 13,
    name: "Mohammed Ali",
    email: "mohammed.ali@example.com",
    role: "Product",
    status: "active",
    lastLogin: "2025-09-25",
    revenue: 12500,
  },
  {
    id: 14,
    name: "Nadia Petrova",
    email: "nadia.petrova@example.com",
    role: "HR",
    status: "active",
    lastLogin: "2025-10-01",
    revenue: 0,
  },
  {
    id: 15,
    name: "Omar Haddad",
    email: "omar.haddad@example.com",
    role: "Engineer",
    status: "paused",
    lastLogin: "2025-09-20",
    revenue: 4700,
  },
  {
    id: 16,
    name: "Priya Singh",
    email: "priya.singh@example.com",
    role: "Support",
    status: "active",
    lastLogin: "2025-10-06",
    revenue: 3100,
  },
  {
    id: 17,
    name: "Quinn Parker",
    email: "quinn.parker@example.com",
    role: "Analytics",
    status: "active",
    lastLogin: "2025-09-27",
    revenue: 8900,
  },
  {
    id: 18,
    name: "Riko Sato",
    email: "riko.sato@example.com",
    role: "Engineer",
    status: "active",
    lastLogin: "2025-10-03",
    revenue: 7600,
  },
  {
    id: 19,
    name: "Samir Desai",
    email: "samir.desai@example.com",
    role: "Sales",
    status: "inactive",
    lastLogin: "2025-06-18",
    revenue: 2100,
  },
  {
    id: 20,
    name: "Tara O'Neill",
    email: "tara.oneill@example.com",
    role: "Designer",
    status: "active",
    lastLogin: "2025-10-04",
    revenue: 5400,
  },
];
